### ISSUE TITLE
Crafting heads has stopped working with 5.1.10

### ISSUE THREAD

**Issue by steve4744** [Thatsmusic99/HeadsPlus#14]
### Short summary of issue
Crafting heads produces nothing.
### Server version
1.13.2
### HeadsPlus version
5.1.10
### Detailed description (how you found it, what you were doing at the time)
It works on 5.1.9. Upgrading to 5.1.10 breaks it. Tried with completely new config files
 `craft-heads: true,
    disable-crafting: false`
### Expected behaviour
creates a head
### Actual behaviour
creates nothing - no errors in console
### Steps to reproduce
try to craft a head with HP 5.1.10
### Any last notes?
checked for the "Material.xxxx" issue, and fixed the silver sheep issue, but didn't help.

**Comment by Thatsmusic99** [comment]
Will double check later.

**Comment by Thatsmusic99** [comment]
Thank you. I do appreciate your comment whilst things aren't at their greatest for both me and the plugin, although (I don't know if you've seen this on Discord or not) I do plan on publishing future versions on here temporarily so I will let you know when the jar is uploaded on here.

Once everything is sorted I will return to working on Spigot again. Once again thank you, and thanks for reporting all the issues HeadsPlus has had. Year 11 at school has forced me into running low on time to work on the plugin but I've got a break to make a comeback whilst I can.

**Comment by Thatsmusic99** [comment]
Reproduced this in 1.13.2 Spigot but got EXTREMELY unexpected results:

- Tested with blaze head, which is at the start of the default crafting.yml, reproduced the issue.
- Tested with zombie head, which is at the very end of the default crafting.yml, reproduced the issue.
- Tested with phantom head, which didn't even have any kind of "name" in heads.yml given, and the issue WASN'T reproduced.

I think I know what I've done now.

**Comment by Thatsmusic99** [comment]
Fixed here. https://github.com/Thatsmusic99/HeadsPlus/releases/tag/v5.1.11

**Comment by steve4744** [comment]
Hi, thanks yeah most of them work now.
The only ones that don't work for me are:
cod, turtle_helmet, pufferfish, white_wool, shulker_shell and phantom_membrane.

Do I need to do any configuration for these to work? When I added a name for cod in heads.yml, crafting created a head but just an alex player head. None of the coloured wool makes a sheep's head either.
Thanks,
Steve

**Comment by steve4744** [comment]
Sorry pufferfish, turtles and shulker work fine when its configured properly - oops.
Cod and phantom_membrane look to be configured ok, but just create a player head.
The sheep I think are already configured, but I can't get any colour wool to work.

**Comment by Thatsmusic99** [comment]
Did ask you about this over Discord, but are the phantom and cod heads using custom textures or simply player names?

Again working on sheep colours now. And probably re-formatting crafting.yml a bit more so enough of the sheepI nonsense.

**Comment by Thatsmusic99** [comment]
Reproduced and working on.

**Comment by steve4744** [comment]
Brilliant thanks. The MHF phantom is fine now (typo in config), but the custom texture ones don't seem to be picking up the texture.

**Comment by Thatsmusic99** [comment]
Fixed in https://github.com/Thatsmusic99/HeadsPlus/releases/tag/v5.2

**Comment by steve4744** [comment]
Crafting sheep now works perfectly. But I still can't craft some other stuff, like cod for example.
headsx.yml
```
cod:
    database: true
    encode: false
    displayname: '&8[&cCod&8]'
    texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzg5MmQ3ZGQ2YWFkZjM1Zjg2ZGEyN2ZiNjNkYTRlZGRhMjExZGY5NmQyODI5ZjY5MTQ2MmE0ZmIxY2FiMCJ9fX0
    price: default
    section: animals
```

crafting.yml
```
cod:
  ingredients:
  - COD
```

heads.yml
```
cod:
  name:
  - HP#cod
  display-name: cod
  price: 5.4
  chance: 30
  interact-name: Cod
  mask-effects: []
  mask-amplifiers: []
  lore:
  - '&7Price: &6{price}'
  - '&7Type: &a{type}'
```


It can't be crafted but the correct head does appear in the shop, but the price is 10.0 even though I've tried to change it to 5.4(above).
Also get an npe when the server starts:
```
[01:24:09 ERROR]: [HeadsPlus] Error thrown creating head for cod. Please check the report for details.
[01:24:09 WARN]: java.lang.NullPointerException
[01:24:09 WARN]:        at io.github.thatsmusic99.headsplus.config.headsx.HeadsPlusConfigHeadsX.getSkull(HeadsPlusConfigHeadsX.java:132)
[01:24:09 WARN]:        at io.github.thatsmusic99.headsplus.crafting.RecipeEnumUser.addEnumToConfig(RecipeEnumUser.java:160)
[01:24:09 WARN]:        at io.github.thatsmusic99.headsplus.crafting.RecipeEnumUser.<init>(RecipeEnumUser.java:26)
[01:24:09 WARN]:        at io.github.thatsmusic99.headsplus.events.JoinEvent$2.run(JoinEvent.java:57)
[01:24:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76)
[01:24:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[01:24:09 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[01:24:09 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[01:24:09 WARN]:        at java.lang.Thread.run(Unknown Source)
[01:24:09 ERROR]: [HeadsPlus] HeadsPlus has failed to execute this task. An error report has been made in /plugins/HeadsPlus/debug
```

**Comment by Thatsmusic99** [comment]
That is extremely odd... Will try and reproduce.

**Comment by Thatsmusic99** [comment]
Can't reproduce the error but seem to be experiencing issues with crafting the cod head. Will try and find the root cause.

**Comment by Thatsmusic99** [comment]
Should hopefully be fixed in release v5.2.1 which is also going to be released on Spigot.

**Comment by steve4744** [comment]
Confirmed fixed in 5.2.1.
Thanks for persevering with this.
