### ISSUE TITLE
[BUG] Error thrown when creating the head

### ISSUE THREAD

**Issue by Gurbiel** [Thatsmusic99/HeadsPlus#28]
## FIRST-HAND CHECK - ARE YOU USING THE LATEST VERSION/SNAPSHOT OF HEADSPLUS?
Yes, I downloaded the newest version on spigot today.

### Description of the bug
Some heads are using default player texture

### Have you been able to reproduce the bug more than once?
Every time when starting the server

### Has a debug report been generated? 
/headsplus debug dump did not work (I tried both client and server console)

### Required information
- Server version: 1.16.1
- HeadsPlus version: v6.10.11
- Whether or not the plugin uses MySQL: no
- Server type (e.g Spigot, Paper): PaperMC (build 108)
- Uses Vault: yes
- I'm using only the heads that come with default config (no custom heads)

## Additional information
latest log: https://hastebin.com/efozeretas.sql

**Comment by Thatsmusic99** [comment]
Can you send your mobs.yml and customheads.yml files?

**Comment by Gurbiel** [comment]
Mobs.yml: https://hastebin.com/ipuhajurin.cs
Customheads.yml: https://hastebin.com/sibiwunaje.coffeescript

**Comment by Thatsmusic99** [comment]
For whatever reason, your customheads.yml file didn't update correctly; try resetting the file and reloading the plugin from there. I thought I fixed this bug a while ago and I don't get why it disappeared. If you updated to a version before this that didn't contain the fix though, that *may* be why.

As for the dump command, I believe that is a permission issue. I will attempt to introduce a workaround for it in the following update.

**Comment by Gurbiel** [comment]
I deleted both files and after restarting everything works fine. Maybe it's my fault, because I didn't update in a while and skipped some versions. Thanks for your help!

Dump still doesn't work though. Should I close this thread?

**Comment by Thatsmusic99** [comment]
It's all good, and I should be able to handle the dump command (and others) in my own time. My current perception is that it's just a permissions problem which I can resolve easily myself.

**Comment by Gurbiel** [comment]
Okay, again, thanks for your help!
